export const 
GETLIST = 'GETLIST',
GETLOADER= 'GETLOADER',
CALLLIST='CALLLIST',
CALL_SIGNUP = 'CALL_SIGNUP',
CALL_LOGIN = 'CALL_LOGIN',
LOG_OUT = 'LOG_OUT',
AUTH_RESULT='AUTH_RESULT',
LOG_OUT_USER='LOG_OUT_USER'